---
title: "NYC Restaurant Inspection Results"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Boxplot

```{r}
## Extract data for zip-code = 10032
zip_box = 
  rest_inspec %>% 
  janitor::clean_names() %>% 
  filter(zipcode == "10032") %>% 
  drop_na(score) %>% 
  mutate(
    street = as.factor(street),
    street = fct_recode(
      street, 
      "WEST 169TH STREET" = "W 169TH ST",
      "West 168TH STREET" = "W 168TH ST",
      "West 168TH STREET" = "WEST 168 STREET",
      "West 168TH STREET" = "WEST  168 STREET",
      "HAVEN AVENUE" = "HAVEN AVE",
      "EDWARD M MORGAN PLACE" = "EDWARD M MORGAN PL",
      "WEST 172TH STREET" = "WEST  172 STREET",
      "AUDUBON AVENUE" = "AUDUBON AVE",
      "ST NICHOLAS AVENUE" = "ST NICHOLAS PLACE",
      "ST NICHOLAS AVENUE" = "SAINT NICHOLAS AVE",
      "AMSTERDAM AVENUE" = "AMSTERDAM AVE"
    )
  ) %>% 
  plot_ly(
    x = ~street, y = ~score, type = "box"
  )

zip_box
```

Column {data-width=350}
-----------------------------------------------------------------------

### Histogram

```{r}
ABC_hist = 
  rest_inspec %>%
  filter(grade %in% c("A", "B", "C"), !(boro == "Missing")) %>% 
  mutate(
    boro = as.factor(boro),
    grade = as.factor(grade)
  ) %>% 
  group_by(boro, grade) %>% 
  count(boro, grade) %>% 
  plot_ly(
    x = ~boro, y = ~n, color = ~grade, type = "bar"
  )

ABC_hist
```

### Scatterplot

```{r}
score_point = 
  rest_inspec %>%
  filter(grade %in% c("A", "B", "C"), boro == "BRONX") %>% 
  drop_na(score) %>% 
  mutate(
    grade = as.factor(grade)
  ) %>% 
  plot_ly(
    x = ~grade, y = ~score, type = "scatter", mode = "markers"
  )

score_point
```